prelude = "prelude"
autoIndex = true

[[articles]]
name = "0.19.1-release-notes"
title = "Elvish 0.19.1 Release Notes"
timestamp = "2023-03-05"

[[articles]]
name = "0.18.0-release-notes"
title = "Elvish 0.18.0 Release Notes"
timestamp = "2022-03-20"

[[articles]]
name = "0.17.0-release-notes"
title = "Elvish 0.17.0 Release Notes"
timestamp = "2021-12-10"

[[articles]]
name = "0.16.0-release-notes"
title = "Elvish 0.16.0 Release Notes"
timestamp = "2021-08-21"

[[articles]]
name = "0.15.0-release-notes"
title = "Elvish 0.15.0 Release Notes"
timestamp = "2021-01-30"

[[articles]]
name = "0.14.1-release-notes"
title = "Elvish 0.14.1 Release Notes"
timestamp = "2020-08-16"

[[articles]]
name = "0.14.0-release-notes"
title = "Elvish 0.14.0 Release Notes"
timestamp = "2020-07-05"

[[articles]]
name = "0.13.1-release-notes"
title = "Elvish 0.13.1 Release Notes"
timestamp = "2020-03-21"

[[articles]]
name = "0.13-release-notes"
title = "Elvish 0.13 Release Notes"
timestamp = "2020-01-01"

[[articles]]
name = "0.12-release-notes"
title = "Elvish 0.12 Release Notes"
timestamp = "2018-08-01"

[[articles]]
name = "0.11-release-notes"
title = "Elvish 0.11 Release Notes"
timestamp = "2018-01-17"

[[articles]]
name = "newsletter-sep-2017"
title = "Elvish Newsletter, Sep 2017 Issue"
timestamp = "2017-09-17"

[[articles]]
name = "0.10-release-notes"
title = "Elvish 0.10 Release Notes"
timestamp = "2017-09-17"

[[articles]]
name = "newsletter-july-2017"
title = "Elvish Newsletter, July 2017 Issue"
timestamp = "2017-07-10"

[[articles]]
name = "0.9-release-notes"
title = "Elvish 0.9 Release Notes"
timestamp = "2017-07-03"

[[articles]]
name = "live"
title = "The Elvish Website is Officially Live!"
timestamp = "2017-07-03"
